//! parse-report — parse every corpus sentence with the tier-1 grammar and
//! report the ADR 0006 cognitive-load metrics. Measurement only, no gating.

use grammar::{metrics, parse_text, Lexicon};

const CORPUS: &str = "corpus/accept.txt";
const REPORT: &str = "docs/parse-report.md";

fn main() {
    let lexicon = Lexicon::load("lexicon.tsv").expect("lexicon.tsv — run lexgen first");
    let corpus = std::fs::read_to_string(CORPUS).expect("corpus");

    let mut out = String::from(
        "# Parse report\n\n*Generated by parse-report — do not edit.*\n\n\
         Cognitive-load metrics per ADR 0006: peak open dependencies\n\
         (comfortable ceiling ≈ 4), max dependency length, embedding depth,\n\
         right-branching share, and fronted tokens before the main head.\n\n\
         | sentence | open | maxdep | depth | right | fronted |\n\
         |---|---|---|---|---|---|\n",
    );

    let mut failures = Vec::new();
    let (mut n, mut peak_worst, mut open_sum) = (0usize, 0usize, 0usize);
    for line in grammar::units(&corpus) {
        let line = line.replace('\n', " ⏎ ");
        let line = line.as_str();
        match parse_text(&lexicon, &line.replace(" ⏎ ", "\n")) {
            Ok(tree) => {
                let m = metrics(&tree);
                n += 1;
                open_sum += m.peak_open_deps;
                peak_worst = peak_worst.max(m.peak_open_deps);
                out.push_str(&format!(
                    "| {line} | {} | {} | {} | {:.0}% | {} |\n",
                    m.peak_open_deps,
                    m.max_dep_len,
                    m.embedding_depth,
                    m.right_branching * 100.0,
                    m.fronted
                ));
            }
            Err(e) => failures.push(format!("{line} — {e}")),
        }
    }

    out.push_str(&format!(
        "\n**Aggregate:** {n} sentences parsed; mean peak-open {:.1}, worst {peak_worst} \
         (ceiling ≈ 4).\n",
        open_sum as f64 / n.max(1) as f64
    ));
    if failures.is_empty() {
        out.push_str("\nAll corpus sentences parse. ✓\n");
    } else {
        out.push_str("\n## FAILURES\n\n");
        for f in &failures {
            out.push_str(&format!("- {f}\n"));
        }
    }

    std::fs::write(REPORT, &out).expect("write report");
    println!(
        "parse-report: {n} parsed, {} failed; report in {REPORT}",
        failures.len()
    );
    if !failures.is_empty() {
        std::process::exit(1);
    }
}
