#!/usr/bin/env bash
# Regenerates docs/coherence-report.md — document-level lint (brief) over every ADR.
set -euo pipefail
cd "$(dirname "$0")/.."
{
echo "# Coherence report: document-level lint over the ADRs"
echo
echo "*Generated by scripts/coherence.sh — do not edit. Measurement only (ADR 0006).*"
echo
for f in docs/adr/*.md; do
  python3 scripts/lint-file.py "$f" --brief | sed 's/^# Document lint: /## /'
  echo
done
} > docs/coherence-report.md
echo "coherence report written to docs/coherence-report.md"
