#!/usr/bin/env python3
"""Sweep all ADRs: per-document minglish parse rate + ranked blockers.
Local-only (extractor + diagnose CLI); writes docs/dogfood-sweep.md."""
import glob, re, subprocess, collections, sys

word_flags = collections.Counter()
style_flags = collections.Counter()
rows = []
for adr in sorted(glob.glob("docs/adr/*.md")):
    sents = subprocess.run(["python3", "scripts/extract-sentences.py", adr],
                           capture_output=True, text=True).stdout.strip().splitlines()
    if not sents:
        continue
    ok = 0
    for i in range(0, len(sents), 20):
        out = subprocess.run(["cargo", "run", "-q", "-p", "diagnose", "--"] + sents[i:i+20],
                             capture_output=True, text=True).stdout
        for line in out.splitlines():
            if line.startswith("✓"):
                ok += 1
            m = re.search(r'WORD: "([^"]+)" is not a minglish word', line)
            if m:
                w = m.group(1).lower().strip(':;,')
                if not re.fullmatch(r"[\d\W]+", w):
                    word_flags[w] += 1
            if "STYLE:" in line:
                style_flags["style-structure"] += 1
    rows.append((adr.split("/")[-1], ok, len(sents)))

with open("docs/dogfood-sweep.md", "w") as f:
    f.write("# Dogfood sweep: minglish parse rate across all ADRs\n\n")
    f.write("*Generated by scripts/dogfood-sweep.py — local linting only.*\n\n")
    f.write("| ADR | parse rate |\n|---|---|\n")
    tot_ok = tot = 0
    for name, ok, n in rows:
        tot_ok += ok; tot += n
        f.write(f"| {name} | {ok}/{n} |\n")
    f.write(f"\n**Aggregate: {tot_ok}/{tot} sentences ({100*tot_ok/max(tot,1):.0f}%)**\n\n")
    f.write("## Blocking words, ranked (gap-interview shortlist)\n\n")
    for w, c in word_flags.most_common(30):
        f.write(f"- {w} ×{c}\n")
print(f"sweep: {tot_ok}/{tot} sentences parse; report in docs/dogfood-sweep.md")
