#!/usr/bin/env bash
# Regenerates docs/showcase.md — a wide-range demonstration of the linter:
# every sanctioned construction, every rejection channel, and the full
# name/quote behavior (ADR 0018). Run from the repo root.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=docs/showcase.md
run() { cargo run -q -p diagnose -- "$@" 2>&1 || true; }

{
echo "# Showcase: the minglish linter, end to end"
echo
echo "*Generated by scripts/showcase.sh — do not edit.*"
echo
echo "## Accepted: one example per sanctioned construction"
echo
echo '```'
run "the agent reads the file" \
    "the server returned an empty result" \
    "the queue is not empty" \
    "the agent does not store the file" \
    "do not delete my report" \
    "the agent must not delete your report" \
    "you cannot delete the lexicon" \
    "if the test fails, then the agent retries the request" \
    "the server stores the message and returns the result" \
    "the test fails or the agent retries the request" \
    "machines find collisions" \
    "every agent retries the request" \
    "no agent can delete the lexicon" \
    "some agents do not retry the request" \
    "every word has one tag" \
    "the server stores a copy of the report at the database" \
    "I have your report" \
    "the agent deleted 3 files" \
    "The agent reads the file" \
    "delete the file"
echo '```'
echo
echo "## Names and quoting (ADR 0018)"
echo
echo "Accepted — capitalized names mid-sentence, quoted identifiers, multi-word names:"
echo
echo '```'
run "the tool Lexgen builds the lexicon" \
    "the database WordNet attests the senses of the words" \
    "the file \"seed.json\" is the source of the truth" \
    "\"seed.json\" is the source of the truth" \
    "the tool Visual Studio Code opens the file"
echo '```'
echo
echo "Multi-word quoted spans — the current limitation, shown explicitly:"
echo "a quoted span of ANY length is ONE opaque thing (an identifier-like"
echo "NP), even if it contains a whole sentence. The quoted content is NOT"
echo "validated as minglish — quotation-as-mention is a separate, undesigned"
echo "construction (see docs/ideas.md, \"Quotation as a construction\")."
echo
echo '```'
run "the agent stores \"delete the file\" in the database" \
    "\"the old build process\" is a report" \
    "the agent stores \"this is not valid minglish at all !!\" in the database"
echo '```'
echo
echo "Rejected — the fail-loud rules (typos never silently become names):"
echo
echo '```'
run "Remove the file" \
    "Lexgen builds the lexicon" \
    "the agent reads the File"
echo '```'
echo
echo "## The repair loop: word-level flags and their fixes"
echo
echo "Each rejection followed by the sentence an agent writes after applying"
echo "the advice:"
echo
echo '```'
run "it fails"
run "the test fails"
echo
run "the agent may fail"
run "the agent can fail"
echo
run "please delete the file"
run "delete the file"
echo
run "the agent deleted three files"
run "the agent deleted 3 files"
echo
run "the agent deleted 1 file"
run "the agent deleted one file"
echo
run "0 agents retry the request"
run "no agent retries the request"
echo
run "the agent deleted 0 files"
run "the agent did not delete files"
echo
run "the same file fails"
run "the file fails"
echo
run "the copies are the same"
run "the copies are identical"
echo '```'
echo
echo "## The repair loop: STYLE flags and their fixes"
echo
echo '```'
run "every agent does not retry the request"
run "no agent retries the request"
run "some agents do not retry the request"
echo
run "no agent must check the input"
run "agents must not check the input"
echo
run "the agent retries no request"
run "the agent does not retry requests"
echo
run "some agent retries the request"
run "some agents retry the request"
echo
run "if the test fails, the agent retries the request"
run "if the test fails, then the agent retries the request"
echo
run "the agent retries the request if the test fails"
run "if the test fails, then the agent retries the request"
echo
run "the agent is opening the file"
run "the agent opens the file"
echo
run "the agent has deleted the file"
run "the agent deleted the file"
echo
run "the file stored in the database fails"
run "the agent stored the file in the database" "the file fails"
echo
run "a files are big"
run "the files are big"
echo
run "the agent deleted 3 file"
run "the agent deleted 3 files"
echo
run "the agent stopped"
run "the agent stopped the process"
echo '```'
echo
echo "## The repair loop: ambiguity and its fix"
echo
echo '```'
run "the agent stores the report in the database with the tool"
run "the agent opened the report with the tool" "the agent stores the report in the database"
echo '```'
echo
echo "Before/after translation previews with costs live in docs/cost-report.md"
echo "and docs/dogfood-cost-report.md."
} > "$OUT"
echo "showcase written to $OUT"
