//! textcost — measures whether minglish makes text cheaper to understand.
//!
//! Cost model: unigram surprisal. zipf = log10(frequency per billion), so a
//! word's surprisal is ≈ 9 − zipf "decades" — a rare word costs more than a
//! common one, which is why word count and byte count are the wrong metrics
//! (ADR 0006 §4). Sentence cost = Σ surprisal over word tokens. This is the
//! cheap, deterministic proxy for contextual surprisal / reading time; an
//! LM-based version can replace it later without changing the corpus.
//!
//! Reads corpus/pairs.tsv (english <TAB> minglish), lints the minglish side
//! against lexicon.tsv (every token must be an enabled surface form — a pair
//! with an invalid minglish side is a build error), writes docs/cost-report.md.

use grammar::{metrics, parse, Lexicon as GrammarLexicon};
use std::collections::{BTreeMap, BTreeSet};
use std::process::exit;

const PAIRS_PATH: &str = "corpus/pairs.tsv";
const REPORT_PATH_DEFAULT: &str = "docs/cost-report.md";
const LEXICON_PATH: &str = "lexicon.tsv";
const ZIPF_PATH: &str = "data/freq/en_zipf.tsv";


/// Surprisal cap for words absent from the frequency table (≈ zipf 0).
const MAX_SURPRISAL: f64 = 9.0;

fn main() {
    let pairs_path = std::env::args().nth(1).unwrap_or_else(|| PAIRS_PATH.to_string());
    let report_path = std::env::args().nth(2).unwrap_or_else(|| REPORT_PATH_DEFAULT.to_string());
    let zipf = load_zipf(ZIPF_PATH);
    let surfaces = load_surfaces(LEXICON_PATH);
    let pairs = load_pairs(&pairs_path);

    // lint: minglish sides must be fully lexicon-valid AND parse in tier 1
    let glex = GrammarLexicon::load(LEXICON_PATH).expect("lexicon for grammar");
    let mut errors = Vec::new();
    let mut trees = Vec::new();
    for (_, mg, _) in &pairs {
        for raw in mg.split_whitespace() {
            // NAMEs (quoted or capitalized, ADR 0018) are not lexicon words
            if raw.starts_with('"') || raw.chars().next().is_some_and(|c| c.is_uppercase()) {
                continue;
            }
            let tok = raw.trim_matches(|c: char| c.is_ascii_punctuation()).to_lowercase();
            if !tok.is_empty() && !surfaces.contains(&tok) {
                errors.push(format!("minglish side uses non-lexicon token \"{tok}\": {mg}"));
            }
        }
        let mut segs = Vec::new();
        let mut ok = true;
        for seg in mg.split(". ").map(|s| s.trim().trim_end_matches('.').trim()).filter(|s| !s.is_empty()) {
            match parse(&glex, seg) {
                Ok(t) => segs.push(t),
                Err(e) => {
                    ok = false;
                    errors.push(format!("minglish sentence does not parse: {seg} — {e}"));
                }
            }
        }
        trees.push(ok.then_some(segs));
    }
    if !errors.is_empty() {
        eprintln!("textcost: {} error(s):", errors.len());
        for e in &errors {
            eprintln!("  - {e}");
        }
        exit(1);
    }

    let cost = |text: &str| -> (usize, f64) {
        let toks = tokens(text);
        let c = toks
            .iter()
            .map(|t| MAX_SURPRISAL - zipf.get(t.as_str()).copied().unwrap_or(0.0))
            .sum();
        (toks.len(), c)
    };

    let mut out = String::from(
        "# Text cost report\n\n*Generated by textcost — do not edit.*\n\n\
         Cost = Σ unigram surprisal (9 − zipf) per word token: the price of a\n\
         word is its improbability, not its length. Lower is cheaper to read.\n\
         Ratio < 1.00 means the minglish side is cheaper than the English\n\
         original.\n\n\
         | # | en words | en cost | mg words | mg cost | ratio |\n\
         |---|---|---|---|---|---|\n",
    );
    let (mut en_total, mut mg_total) = (0.0, 0.0);
    let (mut en_words, mut mg_words) = (0usize, 0usize);
    for (i, (en, mg, _)) in pairs.iter().enumerate() {
        let (ew, ec) = cost(en);
        let (mw, mc) = cost(mg);
        en_total += ec;
        mg_total += mc;
        en_words += ew;
        mg_words += mw;
        out.push_str(&format!(
            "| {} | {ew} | {ec:.1} | {mw} | {mc:.1} | {:.2} |\n",
            i + 1,
            mc / ec
        ));
    }
    out.push_str(&format!(
        "\n**Aggregate:** {} pairs — words {en_words} → {mg_words} ({:+.0}%), \
         cost {en_total:.1} → {mg_total:.1} (**ratio {:.2}**)\n\n",
        pairs.len(),
        100.0 * (mg_words as f64 - en_words as f64) / en_words as f64,
        mg_total / en_total
    ));
    out.push_str("## Before → after\n\n");
    for (i, ((en, mg, drops), tree)) in pairs.iter().zip(&trees).enumerate() {
        let (ew, ec) = cost(en);
        let (mw, mc) = cost(mg);
        out.push_str(&format!("**{}.** BEFORE ({ew} words, cost {ec:.1})\n", i + 1));
        out.push_str(&format!("> {en}\n\n"));
        let segs = tree.as_ref().expect("all sides parse");
        let ms: Vec<_> = segs.iter().map(metrics).collect();
        let peak = ms.iter().map(|m| m.peak_open_deps).max().unwrap_or(0);
        let right = ms.iter().map(|m| m.right_branching).sum::<f64>() / ms.len().max(1) as f64;
        out.push_str(&format!(
            "AFTER ({mw} words, cost {mc:.1}, **{:.0}%** of original) — \
             {} sentence(s), each parses uniquely ✓, peak-open {peak}, right-branching {:.0}%\n",
            100.0 * mc / ec,
            ms.len(),
            right * 100.0
        ));
        out.push_str(&format!("> {}\n\n", display(mg)));
        if drops.is_empty() {
            out.push_str("Declared loss: none (lossless per ADR 0012)\n\n");
        } else {
            out.push_str(&format!("Declared loss: {drops}\n\n"));
        }
    }
    out.push_str(
        "\n*Caveats: unigram surprisal ignores context and structure; meaning\n\
         preservation across a pair is a human judgment; the English sides\n\
         are hand-picked, not sampled. Directional evidence only.*\n",
    );

    std::fs::write(&report_path, &out).expect("write report");
    println!(
        "textcost: {} pairs, aggregate cost ratio {:.2} (mg/en); report in {report_path}",
        pairs.len(),
        mg_total / en_total
    );
}

/// Presentation form: capitalize each sentence start; "i" renders as "I".
/// (The canonical corpus form stays lowercase.)
fn display(mg: &str) -> String {
    mg.split(". ")
        .map(|seg| {
            let seg = seg
                .split_whitespace()
                .map(|w| if w == "i" { "I".to_string() } else { w.to_string() })
                .collect::<Vec<_>>()
                .join(" ");
            let mut c = seg.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => seg,
            }
        })
        .collect::<Vec<_>>()
        .join(". ")
}

fn tokens(text: &str) -> Vec<String> {
    text.split_whitespace()
        .map(|t| {
            t.trim_matches(|c: char| c.is_ascii_punctuation())
                .to_lowercase()
        })
        .filter(|t| !t.is_empty())
        .collect()
}

fn load_zipf(path: &str) -> BTreeMap<String, f64> {
    let text = std::fs::read_to_string(path).expect("zipf table — run scripts/fetch-data.sh");
    text.lines()
        .filter(|l| !l.starts_with('#'))
        .filter_map(|l| {
            let (w, z) = l.split_once('\t')?;
            Some((w.to_string(), z.parse().ok()?))
        })
        .collect()
}

fn load_surfaces(path: &str) -> BTreeSet<String> {
    let text = std::fs::read_to_string(path).expect("lexicon.tsv — run lexgen first");
    text.lines()
        .filter(|l| !l.starts_with('#'))
        .filter_map(|l| {
            let mut f = l.split('\t');
            let (surface, kind) = (f.next()?, f.next()?);
            (kind == "form").then(|| surface.to_string())
        })
        .collect()
}

fn load_pairs(path: &str) -> Vec<(String, String, String)> {
    let text = std::fs::read_to_string(path).expect("pairs corpus");
    text.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .filter_map(|l| {
            let mut f = l.split('\t');
            let (en, mg) = (f.next()?, f.next()?);
            let drops = f.next().unwrap_or("").trim().to_string();
            Some((en.trim().to_string(), mg.trim().to_string(), drops))
        })
        .collect()
}
